# Generated by Django 3.2.7 on 2021-09-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
                ('points', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earlier_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_earlier', to='main.course')),
                ('later_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_later', to='main.course')),
            ],
            options={
                'unique_together': {('earlier_course', 'later_course')},
            },
        ),
        migrations.CreateModel(
            name='Contained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_course1', to='main.course')),
                ('course2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_course2', to='main.course')),
            ],
            options={
                'unique_together': {('course1', 'course2')},
            },
        ),
    ]
