# Generated by Django 3.2.7 on 2021-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contained',
            name='course1',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='contained',
            name='course2',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='earlier_course',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='later_course',
            field=models.CharField(max_length=6),
        ),
        migrations.CreateModel(
            name='Adjacent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.CharField(max_length=6)),
                ('required', models.CharField(max_length=6)),
            ],
            options={
                'unique_together': {('required', 'requires')},
            },
        ),
    ]
