# Generated by Django 3.2.7 on 2021-09-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210918_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='earlier_courses',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('earlier_courses', 'later_course')},
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='earlier_course',
        ),
    ]
